stages:
  split:
    cmd: python src/data/split.py
    deps:
    - data/raw_data/raw.csv
    - src/data/split.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/normalize.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/normalize.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  grid_search:
    cmd: python src/models/grid_search.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/models/grid_search.py
    outs:
    - models/best_params.pkl
  train:
    cmd: python src/models/train.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/train.py
    outs:
    - models/trained_model.pkl
  eval:
    cmd: python src/models/eval.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/trained_model.pkl
    outs:
    - data/y_pred.csv
    metrics:
    - metrics/scores.json:
        cache: false
